services:
  fb-emm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fb-emm
    restart: unless-stopped
    ports:
      - "5055:5055"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 10.80.226.101
      - 10.80.226.102
      - 10.80.226.103
      - 10.80.226.104       # replace with your company DNS server
    dns_search:
      - company.local   # replace with your internal DNS domain
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 5055
      OPEN_BROWSER: 0
      CONTAINER: 1
      FORCE_CHROME_HEADLESS: 1
      CHROME_BINARY: /usr/bin/chromium
    volumes:
      - ./data:/app/data
      - ./diagnostics:/app/diagnostics
    shm_size: "1gb"

    networks:
      proxy:
        aliases:
          - fb-emm

networks:
  proxy:
    driver: bridge
    external: true
